import { BeeAnime } from "@/components/Models/BeeAnime";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import Head from "next/head";
import { Suspense, useRef, useState } from "react";
import { Vector3 } from "three";
import Lottie from "lottie-react";
import Animation from "../public/animation.json";

function Rig() {
  const [vec] = useState(() => new Vector3());
  const { camera, pointer } = useThree();
  useFrame(() => {
    if (innerWidth > 900) {
      if (window.scrollY <= 0) {
        camera.position.lerp(
          vec.set(pointer.x * 0.1, pointer.y * 0.1, 5),
          0.01
        );
      }
    }
  });
  return <group />;
}

export default function Home() {
  const background = useRef<HTMLDivElement>(null);

  return (
    <>
      <Head>
        <title>Bee Application</title>
        <meta name="description" content="Generated by Next Js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={background} className="background" />
      <main className="render">
        <Canvas gl={{ toneMappingExposure: 0.8 }}>
          <Rig />
          <Suspense fallback={null}>
            <BeeAnime backgroundRef={background} />
          </Suspense>
        </Canvas>
      </main>
      <main className="msg">
        <Lottie animationData={Animation} loop className="msg_icon" />
        <h1>Please Rotate Your Mobile</h1>
      </main>
    </>
  );
}
